import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ 
	subsets: ['latin'],
	variable: "--font-inter-normal" 
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children } : { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={`${inter.className} min-h-screen`}>
				<nav>
					<div>Logo here</div>
					<ul>
						<li>
							<a href="/whetstones">whetstones</a>
						</li>

						<li>
							<a href="/kitchenknives">kitchenknives</a>
						</li>
					</ul>
				</nav>
				{/* children will always be pages */}
				{children} 
			</body>
		</html>
	)
}
